routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::resource('typeProducts', App\Http\Controllers\TypeProductController::class);

Route::resource('products', App\Http\Controllers\ProductController::class);

Route::resource('typeOperations', App\Http\Controllers\TypeOperationController::class);

Route::resource('operations', App\Http\Controllers\OperationController::class);

Route::resource('operationProducts', App\Http\Controllers\OperationProductController::class);

Route::resource('images', App\Http\Controllers\ImageController::class);

Route::resource('imageProducts', App\Http\Controllers\ImageProductController::class);




Route::view('contact', 'pullo/contact');

app/Models/OperationProduct.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class OperationProduct
 * @package App\Models
 * @version July 9, 2021, 12:24 am UTC
 *
 * @property integer $prix
 * @property integer $quantite
 * @property string $description
 * @property integer $operation_id
 * @property integer $product_id
 * @property string $created_at
 */
class OperationProduct extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'operation_products';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'prix',
        'quantite',
        'description',
        'operation_id',
        'product_id',
        'created_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'prix' => 'integer',
        'quantite' => 'integer',
        'description' => 'string',
        'operation_id' => 'integer',
        'product_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'prix' => 'required',
        'quantite' => 'required',
        'operation_id' => 'required',
        'product_id' => 'required'
    ];

    
}

app/Http/Controllers/OperationProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOperationProductRequest;
use App\Http\Requests\UpdateOperationProductRequest;
use App\Repositories\OperationProductRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class OperationProductController extends AppBaseController
{
    /** @var  OperationProductRepository */
    private $operationProductRepository;

    public function __construct(OperationProductRepository $operationProductRepo)
    {
        $this->operationProductRepository = $operationProductRepo;
    }

    /**
     * Display a listing of the OperationProduct.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $operationProducts = $this->operationProductRepository->paginate(10);

        return view('operation_products.index')
            ->with('operationProducts', $operationProducts);
    }

    /**
     * Show the form for creating a new OperationProduct.
     *
     * @return Response
     */
    public function create()
    {
        return view('operation_products.create');
    }

    /**
     * Store a newly created OperationProduct in storage.
     *
     * @param CreateOperationProductRequest $request
     *
     * @return Response
     */
    public function store(CreateOperationProductRequest $request)
    {
        $input = $request->all();

        $operationProduct = $this->operationProductRepository->create($input);

        Flash::success('Operation Product saved successfully.');

        return redirect(route('operationProducts.index'));
    }

    /**
     * Display the specified OperationProduct.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $operationProduct = $this->operationProductRepository->find($id);

        if (empty($operationProduct)) {
            Flash::error('Operation Product not found');

            return redirect(route('operationProducts.index'));
        }

        return view('operation_products.show')->with('operationProduct', $operationProduct);
    }

    /**
     * Show the form for editing the specified OperationProduct.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $operationProduct = $this->operationProductRepository->find($id);

        if (empty($operationProduct)) {
            Flash::error('Operation Product not found');

            return redirect(route('operationProducts.index'));
        }

        return view('operation_products.edit')->with('operationProduct', $operationProduct);
    }

    /**
     * Update the specified OperationProduct in storage.
     *
     * @param int $id
     * @param UpdateOperationProductRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOperationProductRequest $request)
    {
        $operationProduct = $this->operationProductRepository->find($id);

        if (empty($operationProduct)) {
            Flash::error('Operation Product not found');

            return redirect(route('operationProducts.index'));
        }

        $operationProduct = $this->operationProductRepository->update($request->all(), $id);

        Flash::success('Operation Product updated successfully.');

        return redirect(route('operationProducts.index'));
    }

    /**
     * Remove the specified OperationProduct from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $operationProduct = $this->operationProductRepository->find($id);

        if (empty($operationProduct)) {
            Flash::error('Operation Product not found');

            return redirect(route('operationProducts.index'));
        }

        $this->operationProductRepository->delete($id);

        Flash::success('Operation Product deleted successfully.');

        return redirect(route('operationProducts.index'));
    }
}

resources/views/operation_products/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Operation Product</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'operationProducts.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('operation_products.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('operationProducts.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/operation_products/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Operation Product</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($operationProduct, ['route' => ['operationProducts.update', $operationProduct->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('operation_products.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('operationProducts.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/operation_products/fields.blade.php
<!-- Prix Field -->
<div class="form-group col-sm-6">
    {!! Form::label('prix', 'Prix:') !!}
    {!! Form::number('prix', null, ['class' => 'form-control']) !!}
</div>

<!-- Quantite Field -->
<div class="form-group col-sm-6">
    {!! Form::label('quantite', 'Quantite:') !!}
    {!! Form::number('quantite', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Operation Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('operation_id', 'Operation Id:') !!}
    {!! Form::select('operation_id', $operationItems, null, ['class' => 'form-control custom-select']) !!}
</div>


<!-- Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_id', 'Product Id:') !!}
    {!! Form::select('product_id', $productItems, null, ['class' => 'form-control custom-select']) !!}
</div>


<!-- Created At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_at', 'Created At:') !!}
    {!! Form::text('created_at', null, ['class' => 'form-control']) !!}
</div>

resources/views/operation_products/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Operation Products</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('operationProducts.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('operation_products.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        @include('adminlte-templates::common.paginate', ['records' => $operationProducts])
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/operation_products/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Operation Product Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('operationProducts.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('operation_products.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/operation_products/show_fields.blade.php
<!-- Prix Field -->
<div class="col-sm-12">
    {!! Form::label('prix', 'Prix:') !!}
    <p>{{ $operationProduct->prix }}</p>
</div>

<!-- Quantite Field -->
<div class="col-sm-12">
    {!! Form::label('quantite', 'Quantite:') !!}
    <p>{{ $operationProduct->quantite }}</p>
</div>

<!-- Description Field -->
<div class="col-sm-12">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $operationProduct->description }}</p>
</div>

<!-- Operation Id Field -->
<div class="col-sm-12">
    {!! Form::label('operation_id', 'Operation Id:') !!}
    <p>{{ $operationProduct->operation_id }}</p>
</div>

<!-- Product Id Field -->
<div class="col-sm-12">
    {!! Form::label('product_id', 'Product Id:') !!}
    <p>{{ $operationProduct->product_id }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $operationProduct->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $operationProduct->updated_at }}</p>
</div>

resources/views/operation_products/table.blade.php
<div class="table-responsive">
    <table class="table" id="operationProducts-table">
        <thead>
        <tr>
            <th>Prix</th>
        <th>Quantite</th>
        <th>Description</th>
        <th>Operation Id</th>
        <th>Product Id</th>
        <th>Created At</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($operationProducts as $operationProduct)
            <tr>
                <td>{{ $operationProduct->prix }}</td>
            <td>{{ $operationProduct->quantite }}</td>
            <td>{{ $operationProduct->description }}</td>
            <td>{{ $operationProduct->operation_id }}</td>
            <td>{{ $operationProduct->product_id }}</td>
            <td>{{ $operationProduct->created_at }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['operationProducts.destroy', $operationProduct->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('operationProducts.show', [$operationProduct->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('operationProducts.edit', [$operationProduct->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>