routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::resource('typeProducts', App\Http\Controllers\TypeProductController::class);

Route::resource('products', App\Http\Controllers\ProductController::class);

Route::resource('typeOperations', App\Http\Controllers\TypeOperationController::class);

Route::resource('operations', App\Http\Controllers\OperationController::class);

Route::resource('operationProducts', App\Http\Controllers\OperationProductController::class);

Route::resource('images', App\Http\Controllers\ImageController::class);

Route::resource('imageProducts', App\Http\Controllers\ImageProductController::class);




Route::view('contact', 'pullo/contact');

app/Models/TypeOperation.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class TypeOperation
 * @package App\Models
 * @version July 9, 2021, 12:23 am UTC
 *
 * @property string $name
 * @property string $description
 */
class TypeOperation extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'type_operations';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];

    
}

app/Http/Controllers/TypeOperationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTypeOperationRequest;
use App\Http\Requests\UpdateTypeOperationRequest;
use App\Repositories\TypeOperationRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TypeOperationController extends AppBaseController
{
    /** @var  TypeOperationRepository */
    private $typeOperationRepository;

    public function __construct(TypeOperationRepository $typeOperationRepo)
    {
        $this->typeOperationRepository = $typeOperationRepo;
    }

    /**
     * Display a listing of the TypeOperation.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $typeOperations = $this->typeOperationRepository->paginate(10);

        return view('type_operations.index')
            ->with('typeOperations', $typeOperations);
    }

    /**
     * Show the form for creating a new TypeOperation.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_operations.create');
    }

    /**
     * Store a newly created TypeOperation in storage.
     *
     * @param CreateTypeOperationRequest $request
     *
     * @return Response
     */
    public function store(CreateTypeOperationRequest $request)
    {
        $input = $request->all();

        $typeOperation = $this->typeOperationRepository->create($input);

        Flash::success('Type Operation saved successfully.');

        return redirect(route('typeOperations.index'));
    }

    /**
     * Display the specified TypeOperation.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeOperation = $this->typeOperationRepository->find($id);

        if (empty($typeOperation)) {
            Flash::error('Type Operation not found');

            return redirect(route('typeOperations.index'));
        }

        return view('type_operations.show')->with('typeOperation', $typeOperation);
    }

    /**
     * Show the form for editing the specified TypeOperation.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeOperation = $this->typeOperationRepository->find($id);

        if (empty($typeOperation)) {
            Flash::error('Type Operation not found');

            return redirect(route('typeOperations.index'));
        }

        return view('type_operations.edit')->with('typeOperation', $typeOperation);
    }

    /**
     * Update the specified TypeOperation in storage.
     *
     * @param int $id
     * @param UpdateTypeOperationRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTypeOperationRequest $request)
    {
        $typeOperation = $this->typeOperationRepository->find($id);

        if (empty($typeOperation)) {
            Flash::error('Type Operation not found');

            return redirect(route('typeOperations.index'));
        }

        $typeOperation = $this->typeOperationRepository->update($request->all(), $id);

        Flash::success('Type Operation updated successfully.');

        return redirect(route('typeOperations.index'));
    }

    /**
     * Remove the specified TypeOperation from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeOperation = $this->typeOperationRepository->find($id);

        if (empty($typeOperation)) {
            Flash::error('Type Operation not found');

            return redirect(route('typeOperations.index'));
        }

        $this->typeOperationRepository->delete($id);

        Flash::success('Type Operation deleted successfully.');

        return redirect(route('typeOperations.index'));
    }
}

resources/views/type_operations/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Type Operation</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'typeOperations.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('type_operations.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('typeOperations.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/type_operations/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Type Operation</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($typeOperation, ['route' => ['typeOperations.update', $typeOperation->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('type_operations.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('typeOperations.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/type_operations/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

resources/views/type_operations/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Type Operations</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('typeOperations.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('type_operations.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        @include('adminlte-templates::common.paginate', ['records' => $typeOperations])
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/type_operations/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Type Operation Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('typeOperations.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('type_operations.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/type_operations/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $typeOperation->name }}</p>
</div>

<!-- Description Field -->
<div class="col-sm-12">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $typeOperation->description }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $typeOperation->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $typeOperation->updated_at }}</p>
</div>

resources/views/type_operations/table.blade.php
<div class="table-responsive">
    <table class="table" id="typeOperations-table">
        <thead>
        <tr>
            <th>Name</th>
        <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($typeOperations as $typeOperation)
            <tr>
                <td>{{ $typeOperation->name }}</td>
            <td>{{ $typeOperation->description }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['typeOperations.destroy', $typeOperation->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('typeOperations.show', [$typeOperation->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('typeOperations.edit', [$typeOperation->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>