routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::resource('typeProducts', App\Http\Controllers\TypeProductController::class);

Route::resource('products', App\Http\Controllers\ProductController::class);

Route::resource('typeOperations', App\Http\Controllers\TypeOperationController::class);

Route::resource('operations', App\Http\Controllers\OperationController::class);

Route::resource('operationProducts', App\Http\Controllers\OperationProductController::class);

Route::resource('images', App\Http\Controllers\ImageController::class);

Route::resource('imageProducts', App\Http\Controllers\ImageProductController::class);




Route::view('contact', 'pullo/contact');

app/Models/TypeProduct.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class TypeProduct
 * @package App\Models
 * @version July 9, 2021, 12:19 am UTC
 *
 * @property string $name
 * @property string $description
 */
class TypeProduct extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'type_products';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];

    
}

app/Http/Controllers/TypeProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTypeProductRequest;
use App\Http\Requests\UpdateTypeProductRequest;
use App\Repositories\TypeProductRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TypeProductController extends AppBaseController
{
    /** @var  TypeProductRepository */
    private $typeProductRepository;

    public function __construct(TypeProductRepository $typeProductRepo)
    {
        $this->typeProductRepository = $typeProductRepo;
    }

    /**
     * Display a listing of the TypeProduct.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $typeProducts = $this->typeProductRepository->paginate(10);

        return view('type_products.index')
            ->with('typeProducts', $typeProducts);
    }

    /**
     * Show the form for creating a new TypeProduct.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_products.create');
    }

    /**
     * Store a newly created TypeProduct in storage.
     *
     * @param CreateTypeProductRequest $request
     *
     * @return Response
     */
    public function store(CreateTypeProductRequest $request)
    {
        $input = $request->all();

        $typeProduct = $this->typeProductRepository->create($input);

        Flash::success('Type Product saved successfully.');

        return redirect(route('typeProducts.index'));
    }

    /**
     * Display the specified TypeProduct.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeProduct = $this->typeProductRepository->find($id);

        if (empty($typeProduct)) {
            Flash::error('Type Product not found');

            return redirect(route('typeProducts.index'));
        }

        return view('type_products.show')->with('typeProduct', $typeProduct);
    }

    /**
     * Show the form for editing the specified TypeProduct.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeProduct = $this->typeProductRepository->find($id);

        if (empty($typeProduct)) {
            Flash::error('Type Product not found');

            return redirect(route('typeProducts.index'));
        }

        return view('type_products.edit')->with('typeProduct', $typeProduct);
    }

    /**
     * Update the specified TypeProduct in storage.
     *
     * @param int $id
     * @param UpdateTypeProductRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTypeProductRequest $request)
    {
        $typeProduct = $this->typeProductRepository->find($id);

        if (empty($typeProduct)) {
            Flash::error('Type Product not found');

            return redirect(route('typeProducts.index'));
        }

        $typeProduct = $this->typeProductRepository->update($request->all(), $id);

        Flash::success('Type Product updated successfully.');

        return redirect(route('typeProducts.index'));
    }

    /**
     * Remove the specified TypeProduct from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeProduct = $this->typeProductRepository->find($id);

        if (empty($typeProduct)) {
            Flash::error('Type Product not found');

            return redirect(route('typeProducts.index'));
        }

        $this->typeProductRepository->delete($id);

        Flash::success('Type Product deleted successfully.');

        return redirect(route('typeProducts.index'));
    }
}

resources/views/type_products/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Type Product</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'typeProducts.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('type_products.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('typeProducts.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/type_products/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Type Product</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($typeProduct, ['route' => ['typeProducts.update', $typeProduct->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('type_products.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('typeProducts.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/type_products/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

resources/views/type_products/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Type Products</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('typeProducts.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('type_products.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        @include('adminlte-templates::common.paginate', ['records' => $typeProducts])
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/type_products/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Type Product Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('typeProducts.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('type_products.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/type_products/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $typeProduct->name }}</p>
</div>

<!-- Description Field -->
<div class="col-sm-12">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $typeProduct->description }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $typeProduct->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $typeProduct->updated_at }}</p>
</div>

resources/views/type_products/table.blade.php
<div class="table-responsive">
    <table class="table" id="typeProducts-table">
        <thead>
        <tr>
            <th>Name</th>
        <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($typeProducts as $typeProduct)
            <tr>
                <td>{{ $typeProduct->name }}</td>
            <td>{{ $typeProduct->description }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['typeProducts.destroy', $typeProduct->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('typeProducts.show', [$typeProduct->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('typeProducts.edit', [$typeProduct->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>